### ISSUE TITLE
github에서 PR에서 approval 받아도 merge 버튼 활성화안되는 이슈 수정하기

### ISSUE THREAD

**Issue by kongyoungin** [kongyi123/MyNotePad#26]
다른 개발자의 approval 1개 이상 그리고 build 성공 시 merge button 활성화되도록
branch rule를 적절하게 설정함.

**Comment by kongyi123** [comment]
![Image](https://github.com/kongyi123/MyNotePad/assets/41764694/778c6793-5fc9-42a3-95ea-5f3c3e435e66)



![Image](https://github.com/kongyi123/MyNotePad/assets/41764694/f053ec73-ac3d-4e64-b942-a75faf7ebbca)




![Image](https://github.com/kongyi123/MyNotePad/assets/41764694/ff3cff34-a9a1-400a-b814-d07d435bbe6b)




![Image](https://github.com/kongyi123/MyNotePad/assets/41764694/f0746c58-3734-4bfa-a9e3-bb511edb386c)




![Image](https://github.com/kongyi123/MyNotePad/assets/41764694/b487aef8-1309-4f24-b988-51e7bb64545f)

// build를 빠뜨리지 않고 추가해야줘야 한다. -> 그러지 않으면 required대상으로 되지 않음

**Comment by kongyi123** [comment]
main과 develop/*

위와 같이 브랜치 동일하게 설정해주면 된다.
이 둘만 해주면 된다. 다른 브랜치는 x
